name: Test

on: [push]

jobs:
  make-test:
    name: make-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Bogdanp/setup-racket@v1.15
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'

        # Setup the cache for Racket packages
      - name: Cache Racket packages
        id: cache-racket
        uses: actions/cache@v4
        with:
          path: ~/.local/share/racket
          key: ${{ runner.os }}-racket-${{ hashFiles('.github/workflows/*.yml') }}

      # Only run raco pkg install if we didn't get a cache hit
      - name: Install racket libraries
        if: steps.cache-racket.outputs.cache-hit != 'true'
        run: raco pkg install --auto component brag roman-numeral

      - name: Cache and install C-INTERCAL
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: intercal
          version: 1.0

      - name: Run ick frontend tests
        run: raco test ick-tests.rkt

      - name: Run S-ick implementation tests
        run: raco test sick-test.rkt

      - name: Run fib.i test
        run: |
          ick -b fib.i && ./fib | awk 'NF' > fib.out.ick
          racket fib.i | grep -v '[0-9]' > fib.out.rkt || true
          diff fib.out.ick fib.out.rkt

      - name: Run hanoi.i test
        run: |
          ick -b hanoi.i && echo 'THREE' | ./hanoi | awk 'NF' > hanoi.out.ick
          echo 'THREE' | racket hanoi.i | grep -v '[0-9]' > hanoi.out.rkt || true
          diff hanoi.out.ick hanoi.out.rkt

      - name: Run onceagain.i test
        run: |
          ick -b onceagain.i && ./onceagain | awk 'NF' > onceagain.out.ick
          racket onceagain.i | grep -v '[0-9]' > onceagain.out.rkt || true
          diff onceagain.out.ick onceagain.out.rkt

      - name: Run hello.i test
        run: |
          ick -b hello.i && ./hello | awk 'NF' > hello.out.ick
          racket hello.i | grep -v '^[0-9][0-9]*$' > hello.out.rkt || true
          diff hello.out.ick hello.out.rkt

      - name: Run ignorret.i test
        run: |
          ick -b ignorret.i && ./ignorret | awk 'NF' > ignorret.out.ick
          racket ignorret.i | grep -v '^[0-9][0-9]*$' > ignorret.out.rkt || true
          diff ignorret.out.ick ignorret.out.rkt

      - name: Run beer.i test
        run: |
          ick -b beer.i && ./beer > beer.out.ick
          racket beer.i > beer.out.rkt || true
          diff beer.out.ick beer.out.rkt

      - name: Run life.i test
        run: |
          printf 'ONE ONE\nONE ONE\nONE OH\nFIVE\nSIX\nSIX\nSIX\nSEVEN\nSIX\nSIX\nSEVEN\nOH\n' > life.in
          ick -b life.i && ./life < life.in | awk 'NF' > life.out.ick
          racket life.i < life.in | awk 'NF' > life.out.rkt || true
          diff life.out.ick life.out.rkt
